// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{0}
}

type CodeURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // короткая ссылка
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`   // исходный URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeURL) Reset() {
	*x = CodeURL{}
	mi := &file_proto_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeURL) ProtoMessage() {}

func (x *CodeURL) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeURL.ProtoReflect.Descriptor instead.
func (*CodeURL) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{1}
}

func (x *CodeURL) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CodeURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetShortenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // короткая ссылка
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortenerRequest) Reset() {
	*x = GetShortenerRequest{}
	mi := &file_proto_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortenerRequest) ProtoMessage() {}

func (x *GetShortenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortenerRequest.ProtoReflect.Descriptor instead.
func (*GetShortenerRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{3}
}

func (x *GetShortenerRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetShortenerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // исходный URL
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortenerResponse) Reset() {
	*x = GetShortenerResponse{}
	mi := &file_proto_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortenerResponse) ProtoMessage() {}

func (x *GetShortenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortenerResponse.ProtoReflect.Descriptor instead.
func (*GetShortenerResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{4}
}

func (x *GetShortenerResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetShortenerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetShortenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // исходный URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetShortenerRequest) Reset() {
	*x = SetShortenerRequest{}
	mi := &file_proto_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetShortenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetShortenerRequest) ProtoMessage() {}

func (x *SetShortenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetShortenerRequest.ProtoReflect.Descriptor instead.
func (*SetShortenerRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{5}
}

func (x *SetShortenerRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SetShortenerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // короткая ссылка
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetShortenerResponse) Reset() {
	*x = SetShortenerResponse{}
	mi := &file_proto_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetShortenerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetShortenerResponse) ProtoMessage() {}

func (x *SetShortenerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetShortenerResponse.ProtoReflect.Descriptor instead.
func (*SetShortenerResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{6}
}

func (x *SetShortenerResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SetShortenerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{7}
}

func (x *PingResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codeurl       []*CodeURL             `protobuf:"bytes,1,rep,name=codeurl,proto3" json:"codeurl,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLsResponse) Reset() {
	*x = GetUserURLsResponse{}
	mi := &file_proto_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLsResponse) ProtoMessage() {}

func (x *GetUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLsResponse.ProtoReflect.Descriptor instead.
func (*GetUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserURLsResponse) GetCodeurl() []*CodeURL {
	if x != nil {
		return x.Codeurl
	}
	return nil
}

func (x *GetUserURLsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteShortenerBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          []string               `protobuf:"bytes,1,rep,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortenerBatchRequest) Reset() {
	*x = DeleteShortenerBatchRequest{}
	mi := &file_proto_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortenerBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortenerBatchRequest) ProtoMessage() {}

func (x *DeleteShortenerBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortenerBatchRequest.ProtoReflect.Descriptor instead.
func (*DeleteShortenerBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteShortenerBatchRequest) GetCode() []string {
	if x != nil {
		return x.Code
	}
	return nil
}

type DeleteShortenerBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteShortenerBatchResponse) Reset() {
	*x = DeleteShortenerBatchResponse{}
	mi := &file_proto_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteShortenerBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteShortenerBatchResponse) ProtoMessage() {}

func (x *DeleteShortenerBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteShortenerBatchResponse.ProtoReflect.Descriptor instead.
func (*DeleteShortenerBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteShortenerBatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_server_proto protoreflect.FileDescriptor

const file_proto_server_proto_rawDesc = "" +
	"\n" +
	"\x12proto/server.proto\x12\vgrpc_server\"\a\n" +
	"\x05Empty\"/\n" +
	"\aCodeURL\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"(\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\")\n" +
	"\x13GetShortenerRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\">\n" +
	"\x14GetShortenerResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"'\n" +
	"\x13SetShortenerRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"@\n" +
	"\x14SetShortenerResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"$\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"[\n" +
	"\x13GetUserURLsResponse\x12.\n" +
	"\acodeurl\x18\x01 \x03(\v2\x14.grpc_server.CodeURLR\acodeurl\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"1\n" +
	"\x1bDeleteShortenerBatchRequest\x12\x12\n" +
	"\x04code\x18\x01 \x03(\tR\x04code\"4\n" +
	"\x1cDeleteShortenerBatchResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\xdd\x03\n" +
	"\tShortener\x12=\n" +
	"\bRegister\x12\x12.grpc_server.Empty\x1a\x1d.grpc_server.RegisterResponse\x12S\n" +
	"\fGetShortener\x12 .grpc_server.GetShortenerRequest\x1a!.grpc_server.GetShortenerResponse\x12S\n" +
	"\fSetShortener\x12 .grpc_server.SetShortenerRequest\x1a!.grpc_server.SetShortenerResponse\x125\n" +
	"\x04Ping\x12\x12.grpc_server.Empty\x1a\x19.grpc_server.PingResponse\x12C\n" +
	"\vGetUserURLs\x12\x12.grpc_server.Empty\x1a .grpc_server.GetUserURLsResponse\x12k\n" +
	"\x14DeleteShortenerBatch\x12(.grpc_server.DeleteShortenerBatchRequest\x1a).grpc_server.DeleteShortenerBatchResponseB&Z$internal/shortener/grpc_server/protob\x06proto3"

var (
	file_proto_server_proto_rawDescOnce sync.Once
	file_proto_server_proto_rawDescData []byte
)

func file_proto_server_proto_rawDescGZIP() []byte {
	file_proto_server_proto_rawDescOnce.Do(func() {
		file_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_server_proto_rawDesc), len(file_proto_server_proto_rawDesc)))
	})
	return file_proto_server_proto_rawDescData
}

var file_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_server_proto_goTypes = []any{
	(*Empty)(nil),                        // 0: grpc_server.Empty
	(*CodeURL)(nil),                      // 1: grpc_server.CodeURL
	(*RegisterResponse)(nil),             // 2: grpc_server.RegisterResponse
	(*GetShortenerRequest)(nil),          // 3: grpc_server.GetShortenerRequest
	(*GetShortenerResponse)(nil),         // 4: grpc_server.GetShortenerResponse
	(*SetShortenerRequest)(nil),          // 5: grpc_server.SetShortenerRequest
	(*SetShortenerResponse)(nil),         // 6: grpc_server.SetShortenerResponse
	(*PingResponse)(nil),                 // 7: grpc_server.PingResponse
	(*GetUserURLsResponse)(nil),          // 8: grpc_server.GetUserURLsResponse
	(*DeleteShortenerBatchRequest)(nil),  // 9: grpc_server.DeleteShortenerBatchRequest
	(*DeleteShortenerBatchResponse)(nil), // 10: grpc_server.DeleteShortenerBatchResponse
}
var file_proto_server_proto_depIdxs = []int32{
	1,  // 0: grpc_server.GetUserURLsResponse.codeurl:type_name -> grpc_server.CodeURL
	0,  // 1: grpc_server.Shortener.Register:input_type -> grpc_server.Empty
	3,  // 2: grpc_server.Shortener.GetShortener:input_type -> grpc_server.GetShortenerRequest
	5,  // 3: grpc_server.Shortener.SetShortener:input_type -> grpc_server.SetShortenerRequest
	0,  // 4: grpc_server.Shortener.Ping:input_type -> grpc_server.Empty
	0,  // 5: grpc_server.Shortener.GetUserURLs:input_type -> grpc_server.Empty
	9,  // 6: grpc_server.Shortener.DeleteShortenerBatch:input_type -> grpc_server.DeleteShortenerBatchRequest
	2,  // 7: grpc_server.Shortener.Register:output_type -> grpc_server.RegisterResponse
	4,  // 8: grpc_server.Shortener.GetShortener:output_type -> grpc_server.GetShortenerResponse
	6,  // 9: grpc_server.Shortener.SetShortener:output_type -> grpc_server.SetShortenerResponse
	7,  // 10: grpc_server.Shortener.Ping:output_type -> grpc_server.PingResponse
	8,  // 11: grpc_server.Shortener.GetUserURLs:output_type -> grpc_server.GetUserURLsResponse
	10, // 12: grpc_server.Shortener.DeleteShortenerBatch:output_type -> grpc_server.DeleteShortenerBatchResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_server_proto_init() }
func file_proto_server_proto_init() {
	if File_proto_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_server_proto_rawDesc), len(file_proto_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_server_proto_goTypes,
		DependencyIndexes: file_proto_server_proto_depIdxs,
		MessageInfos:      file_proto_server_proto_msgTypes,
	}.Build()
	File_proto_server_proto = out.File
	file_proto_server_proto_goTypes = nil
	file_proto_server_proto_depIdxs = nil
}
